### ISSUE TITLE
travis build can't find eccodes on centos7 and f27

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/Magics-rpm#10]

**Comment by brancomat** [comment]
But it seems to install eccodes, at least according to:
https://travis-ci.org/ARPA-SIMC/Magics-rpm/jobs/483458080#L503

And we copied eccodes packaging from fedora repo since 2.8.0. The main difference seems to be eccodes version (2.9.2 on latest f28 repo) so I updated eccodes-rpm to 2.9.2 with the same spec/patches, currently building, then I'll retry Magics build

**Comment by dcesari** [comment]
mi aveva lasciato perplesso il log attorno alla l. 503, ma magari ho interpretato male

**Comment by brancomat** [comment]
updating to eccodes 2.9.2 did the trick (don't ask), copr build is still running

there are other build issues on f29 (#11) and rawhide (the ubiquitous "ambiguous python shebang" now treated as error)
