### ISSUE TITLE
tests in f29 build can't load shared library libQt5Core.so.5:

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/Magics-rpm#11]
see https://travis-ci.org/ARPA-SIMC/Magics-rpm/jobs/483458083

**Comment by brancomat** [comment]
see also https://github.com/ARPA-SIMC/provami/issues/33

**Comment by edigiacomo** [comment]
A workaround is https://github.com/fedora-cloud/docker-brew-fedora/issues/66#issuecomment-467146699

**Comment by edigiacomo** [comment]
I have pushed the workaround in the master branch, but I don't close this issue to keep track of the workaround. We close this issue when the workaround can be removed.
