### ISSUE TITLE
Ignore dladdr when building the path of resources in share folder

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/Magics-rpm#15]
In Magics 4.8.0 the path of the resources is built using `dladdr` and the path of the library itself. Unfortunately, the library is installed in `/lib64` and `/usr/lib64` and the former path is checked first. Then, Magics looks for the resources in `/share/magics/` instead of `/usr/share/magics`.

There are two solutions:
1. Set the environment variable `MAGPLUS_HOME=/usr`: if set, Magics use this path instead of using `dladdr`
2. Patch the code of the function `magics::buildSharePath` (in `src/magics.h`)

**Comment by brancomat** [comment]
released patch in 4.8.0-2
