### ISSUE TITLE
Remove rpath 

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/Magics-rpm#16]
```
+ cmake  ...
...
-- install rpath  : $ORIGIN/../lib64
```

`rpath` should be removed (see https://fedoraproject.org/wiki/RPath_Packaging_Draft#Beware_of_Rpath). Moreover, this should solve ARPA-SIMC/arkimaps#83.

**Comment by brancomat** [comment]
Is this fixed by 68c1dc5bc87330ed207cf13cb64a325c7c08f7a9? Can we close the issue?
